### ISSUE TITLE
Remote (non-local) assets?

### ISSUE THREAD

**Issue by xfq** [sidvishnoi/local-assets#1]
Is there a plan to support remote assets? Some specs contain remote assets, but per W3C Pubrules each document on /TR should be self contained.

See also:

* https://www.w3.org/pubrules/doc/rules/?profile=WD#compoundFilesLocation
* https://github.com/w3c/i18n-activity/issues/1023

**Comment by sidvishnoi** [comment]
I think that would be out of scope of this project. Is there a reason they are not checked-in in the repository?

**Comment by sidvishnoi** [comment]
If it's a spec-prod issue, maybe we can add another configuration option "DOWNLOAD_ASSETS"? (If they can't be checked-in in the repo itself)

**Comment by xfq** [comment]
> Is there a reason they are not checked-in in the repository?

See https://www.w3.org/TR/jpan-gap/#issue170_vertical_text for an example. The content in this document (including the images) was automatically extracted from GitHub issues, because it is convenient for people who are not familiar with HTML to contribute content to this document.

**Comment by xfq** [comment]
> If it's a spec-prod issue, maybe we can add another configuration option "DOWNLOAD_ASSETS"? (If they can't be checked-in in the repo itself)

Sounds good to me.

**Comment by sidvishnoi** [comment]
Moved to https://github.com/w3c/spec-prod/issues/32
